### PR TITLE
Testing tic tac toe game with rspec

### PR DESCRIPTION
**Pull request by NataJenkins**
Test cases were made to check the game functionality

### CODE REVIEW

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
### Status: Changes Required!
Hello team! You've done an Ok job but I believe you should add more test cases to your tests and try to cover all logic related methods. For example, you can check the winner method. I believe this is very important. But let me come to the real problem. One of your tests can't pass the test case. I did not understand well, this line 8 when you say be_within(1). I am giving the error message down there as well. Kindly fix this.
rev

When you are done with your code, please submit for a re-review. :100: 
Good luck! :smile_cat: 
If you have any questions about the review, feel free to reach me via Slack.
Eyüp Sercan UYGUR

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle: :stop_sign: 
Hello team again.
Thanks for the fix on the previous submission. However, before moving on you need to implement more test cases with negative and positive options.
all_tic_tac_toe

- [ ] So you can give some time and try to implement some tests for the winner method. Both negative and positive cases to show that your winner method works like charm. :muscle: If your code runs when you try to implement a test case, you can disable this run from the main.rb. :black_circle: 

- [ ] Also, there are commented out code in your grid spec file. Please delete them.

- [ ] When you are done with your tests, you can add a test section on your Readme and explain the usage of your tests and what is your purpose with those tests.

Kindly work on those issues, and submit for a re-review when it's done.
If you have a question about the review, feel free to reach me via Slack.
Eyüp Sercan UYGUR

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey team, 👋

You have done a great job so far, your test coverage is excellent.

### Changes Required ♻️ 
There are still some changes 👇 you need to implement to approve this request 🔍

- [ ] You are required to test all public methods. However, the `update_board` and `player_position` methods in your `Grid` class are testable but are not tested. Please work on this. 

#### Please, make the REQUIRED change and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime**

I would be happy to help! 👩‍💻 

Happy coding 🤓

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 

Congratulations on making all the requested changes and getting this project approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

**Pull request merged**
